### ISSUE TITLE
FLUX MOTIONEYES

### ISSUE THREAD

**Issue by Geulopa** [TinkerTurtle/Sentry-Picam#4]
Good morning

Thanks for your project.
I am currently trying to recover the video stream in motionEyes but it does not work, are there any particular things to do or modify?
Thank you

**Comment by TinkerTurtle** [comment]
Is this for a MP4 file? If not, you might want to try generating a MP4 file with ffmpeg first.

**Comment by Geulopa** [comment]
non je voulais récupérer le flux en direct

**Comment by TinkerTurtle** [comment]
avez-vous essayé http://[URL]/video.h264 ?

**Comment by Geulopa** [comment]
ca ne fonctionne pas

**Comment by TinkerTurtle** [comment]
Est-ce que http://[URL]/video.h264 fonctionne dans votre navigateur ?

**Comment by Geulopa** [comment]
non

**Comment by Geulopa** [comment]
par contre dans VLC quand je rentre cette adresse :http://192.168.0.141:8080/video.h264 cela fonctionne mais pas dans le navigateur ni dans motionEyes

**Comment by TinkerTurtle** [comment]
Vous pouvez également essayer de définir le format d'entrée sur h264 dans MotionEye : https://motion-project.github.io/motion_config.html

Comme cela fonctionne dans VLC, je pense que cela signifie que le flux HTTP devrait fonctionner.

**Comment by Geulopa** [comment]
j'avoue que cela dépasse mes compétences
