### ISSUE TITLE
USB Cam

### ISSUE THREAD

**Issue by Naudnaud25** [TinkerTurtle/Sentry-Picam#5]
Hello

Thank's for this project, much better for me than MotioneyeOS.

My camera work perfecly with a rasp cam inside a 3d print Portal 2  camera.

I would like to use a usb camera (better quality) , but when i plug it, it doesn't work.

Sentry picam work with usb cam ? 

Thx

**Comment by TinkerTurtle** [comment]
Sorry this project is not compatible with USB cams. It requires motion vector support provided from "raspivid".

**Comment by Naudnaud25** [comment]
ok thank's
