### ISSUE TITLE
Spelling error in Web Interface

### ISSUE THREAD

**Issue by fritzlaszlo** [TinkerTurtle/Sentry-Picam#6]
Hi,

sorry, I don't have the means to produce a pull request right now, but I just spotted this little typo in the /www/index.html file on line 60:

`<button type="button" id="btn_modeNight" onclick="cam.set({mode: 'NIGHT'}; modal.close();)">🌙 Night mode</button>`
should be
`<button type="button" id="btn_modeNight" onclick="cam.set({mode: 'NIGHT'}); modal.close();">🌙 Night mode</button>`

The same way as it is in the line above (day mode).

**Comment by TinkerTurtle** [comment]
Thanks! Fixed in https://github.com/TinkerTurtle/Sentry-Picam/commit/12312fbb867638d3162ab384a716694d9d50c1fe
